-- Cambiar la contraseña del SYS y SYSTEM
ALTER USER sys IDENTIFIED BY SYS_ADMIN;
ALTER USER system IDENTIFIED BY SYS_ADMIN;

-- Crear un nuevo usuario
CREATE USER dani IDENTIFIED BY 233271018;
GRANT CONNECT, RESOURCE, DBA TO dani;

EXIT;
